### ISSUE TITLE
profiles-0.8.1-251 has wrong URL

### ISSUE THREAD

**Issue by kusma** [KhronosGroup/Khronos-Schemas#54]
It seems someone made a typo, and published the profiles-0.8.1-251 schema with a dash between the minor version and patch version number instead of a dot.

This means the file is now served from https://schema.khronos.org/vulkan/profiles-0.8-1-251.json instead of https://schema.khronos.org/vulkan/profiles-0.8.1-251.json as one would expect...

**Comment by kusma** [comment]
The problem seems to be in the file-name in !53

**Comment by christophe-lunarg** [comment]
Sorry my mistake... :/

This should be fixed now...
